import type { SchoolDatabase } from "../engine/types";
import referencesJson from "./references.json";
import seedJson from "./schools.seed.json";

/**
 * Bundled school & university fee database for Depok and Bogor.
 * Generated by scripts/build-seed.mjs from the provenance records in data/research/*.json —
 * every fee carries its source URL, access date, academic year and verification status.
 */
export const SEED_DB = seedJson as unknown as SchoolDatabase;

export interface ReferenceSource {
  url: string;
  title?: string;
  publisher?: string;
  sourceType: string;
  publishedDate?: string | null;
  accessedDate: string;
  evidence: string;
}

export interface InflationReference {
  series: string;
  period: string;
  valuePct: number;
  baseYear?: string;
  verbatim: string;
  source: ReferenceSource;
}

export interface PolicyReference {
  topic: string;
  summary: string;
  statusAsOf2026?: string;
  verbatim: string;
  source: ReferenceSource;
}

export interface MarketReference {
  indicator: string;
  asOf: string;
  valuePct: number;
  verbatim: string;
  note?: string;
  source: ReferenceSource;
}

export interface EstimateReference {
  who: string;
  claim: string;
  basis?: string;
  verbatim: string;
  source: ReferenceSource;
}

export interface References {
  inflationSeries: InflationReference[];
  policies: PolicyReference[];
  marketRates: MarketReference[];
  estimates: EstimateReference[];
}

export const REFERENCES = referencesJson as unknown as References;
